version: '3.7'
services:
   db-wp:
     image: mysql:5.7
     container_name: db-wp
     volumes:
      - ./db/data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: nfY7.hXRcs
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: ClHP2@Qn9c
   wordpress:
     depends_on:
       - db-wp
     image: wordpress
     container_name: wp
     ports:
       - "8000:80"
     environment:
       WORDPRESS_DB_HOST: db-wp:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: ClHP2@Qn9c
     volumes:
      - ./wp-content:/var/www/html/wp-content
