version: '3.7'

services:
   dbmysql-wp:
     image: mysql:5.7
     volumes:
      - $HOME/dbmysql-wp:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - dbmysql-wp
     image: wordpress
     ports:
       - "8000:80"
     environment:
       WORDPRESS_DB_HOST: dbmysql-wp:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
      - $HOME/wp-content:/var/www/html/wp-content
