version: '3.7'

services:
   db:
     image: mysql:5.7
     volumes:
      - $HOME/db:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: nfY7.hXRcs
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: ClHP2@Qn9c

   wordpress:
     depends_on:
       - db
     image: wordpress
     ports:
       - "8000:80"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: ClHP2@Qn9c
     volumes:
      - ./wp-content:/var/www/html/wp-content
